# This is a basic workflow to help you get started with Actions

name: Github Action Maven Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout the main branch from Github
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 2 - Setup JDK 1.7
        uses: actions/setup-java@v1
        with:
           java-version: 1.7
           
        
      # Runs a set of commands for building Clean Sweep Maven Project
      - name: Step 3 - Github Actions Building Clean Sweep Maven Project
        run:  mvn -B package --file /home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/cleansweep/pom.xml
        
 
      # Runs a set of commands for building Sensor-Simulator Maven Project
      - name: Step 4 - Github Actions Building Sensor-Simulator Maven Project
        run: | 
            mvn install:install-file -Dfile=/home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/cleansweep/target/cleansweep-0.0.1-SNAPSHOT.jar -DgroupId=com.group9 -DartifactId=cleansweep -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar 
            mvn -B package --file /home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/sensor-simulator/pom.xml
            
         
        # Runs a set of commands for building Control System Maven Project
      - name: Step 5 - Github Actions Building Control System Maven Project
        run: | 
            mvn install:install-file -Dfile=/home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/sensor-simulator/target/sensor-simulator-0.0.1-SNAPSHOT.jar -DgroupId=com.group9 -DartifactId=sensor-simulator -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar 
            mvn -B package --file  /home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/control-system/pom.xml
            
                
      - name: Step 6 - Get the tareget folder path of Clean Sweep Project
        run: | 
         ls -a /home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/cleansweep/target
         
      - name: Step 7 - Get the tareget folder path of Sensor Simulator Project
        run: | 
         ls -a /home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/sensor-simulator/target
         
      - name: Step 8 - Get the tareget folder path of Control System Project
        run: | 
         ls -a /home/runner/work/CleanSweepSimulator_Group2/CleanSweepSimulator_Group2/control-system/target
